source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LocalizedView_Example', :exclusive => true do
  pod 'LocalizedView', :path => '../'
end

target 'LocalizedView_Tests', :exclusive => true do
  pod 'LocalizedView', :path => '../'

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
