source 'https://github.com/CocoaPods/Specs.git'

target 'LocalizedView_Example', :exclusive => true do
  pod 'LocalizedView', :path => '../'
end

target 'LocalizedView_Tests', :exclusive => true do
  pod 'LocalizedView', :path => '../'

  pod 'Kiwi'
end
